"""Add comprehensive client fields

Revision ID: 12ae86f2277c
Revises: b170e14f1347
Create Date: 2025-10-02 10:00:03.008361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ae86f2277c'
down_revision: Union[str, Sequence[str], None] = 'b170e14f1347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.add_column('clients', sa.Column('rg', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('whatsapp', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('clients', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('investment_profile', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('risk_tolerance', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('investment_experience', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('monthly_income', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('net_worth', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('investment_goals', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('clients', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('referral_source', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'clients', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'referral_source')
    op.drop_column('clients', 'tags')
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'last_contact_date')
    op.drop_column('clients', 'created_by')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'investment_goals')
    op.drop_column('clients', 'net_worth')
    op.drop_column('clients', 'monthly_income')
    op.drop_column('clients', 'investment_experience')
    op.drop_column('clients', 'risk_tolerance')
    op.drop_column('clients', 'investment_profile')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'zip_code')
    op.drop_column('clients', 'state')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'neighborhood')
    op.drop_column('clients', 'complement')
    op.drop_column('clients', 'number')
    op.drop_column('clients', 'street')
    op.drop_column('clients', 'whatsapp')
    op.drop_column('clients', 'mobile')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'birth_date')
    op.drop_column('clients', 'rg')
    op.drop_column('clients', 'cpf')
    # ### end Alembic commands ###
